<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>column_code</name>
   <tag></tag>
   <elementGuidId>ca29b070-575a-41cd-85c4-302be16564f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table/thead/tr/th[contains(text(),'code')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
