<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>column_name</name>
   <tag></tag>
   <elementGuidId>4a8f944b-9523-4537-8eff-8b6b3987e107</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table/thead/tr/th[contains(text(),'nama')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
