<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_payAmount</name>
   <tag></tag>
   <elementGuidId>527c45d3-49b1-4aea-85f8-482deacf57e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder = '...jumlah bayar' and @type = 'text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-rltemf > input.chakra-input.css-ksd4gw</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f7d639b1-9584-4fa5-8b9c-85f1660d182e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>...jumlah bayar</value>
      <webElementGuid>11d636de-72b0-403b-99d7-c6c6343c9f13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fd77142d-8b0f-4404-8818-fb257625abf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input css-ksd4gw</value>
      <webElementGuid>fc5149fa-d69a-4648-ab99-6c5c152d3dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>b1231975-05c9-4f51-8a3f-3bfbe41543f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;css-k008qs&quot;]/div[@class=&quot;css-1r35f0l&quot;]/div[@class=&quot;chakra-container css-9rmdie&quot;]/div[@class=&quot;css-1fkz4uk&quot;]/div[@class=&quot;css-1em21z&quot;]/div[@class=&quot;css-113369k&quot;]/div[@class=&quot;css-n4rzf0&quot;]/div[@class=&quot;css-rltemf&quot;]/input[@class=&quot;chakra-input css-ksd4gw&quot;]</value>
      <webElementGuid>b94f4005-cb78-457b-b0f2-654f39dd9c5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[2]</value>
      <webElementGuid>3f6ca35b-c2d6-429c-8a95-4d78213ae3bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div/div[3]/div/div/div/input</value>
      <webElementGuid>42af1f0c-52fd-4efd-927b-106804c08e0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/following::input[1]</value>
      <webElementGuid>3be521bd-b25c-4ccb-bc07-6d5db907b545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='subtotal'])[1]/following::input[1]</value>
      <webElementGuid>497cdcdd-ccd0-49a6-8473-72c216d33942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bayar'])[1]/preceding::input[1]</value>
      <webElementGuid>5b11f8b5-0fbf-47ac-9bd2-478b7232fd65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>f2045146-a54f-4e13-a475-22c266e74d2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '...jumlah bayar' and @type = 'text']</value>
      <webElementGuid>e788d2f7-1c44-48f1-9b38-adf2e6100fb2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
